### ISSUE TITLE
Running the extension inside an incognito window does not open generated report

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/lighthouse#1177]
Running Lighthouse on a website in an incognito window, when the extension generated it opens a new tab with an URL such as `blob:chrome-extension://<EXTENSION-ID>/<REPORT-ID>`. However, incognito disallows accessing this output and displays a HTTP ERROR 404 page. Consequently copying the URL back into a normal Chrome window does show the correct report.

I run Lighthouse inside an incognito window because I have other extensions running that I do not want to interfere with my performance tests.

**Comment by ebidel** [comment]
Another reason to possibly switch away from blob urls is that we never revoke them. From multiple runs of LH:

<img width="659" alt="screen shot 2016-12-19 at 8 49 24 am" src="https://cloud.githubusercontent.com/assets/238208/21321610/6554da70-c5ca-11e6-9485-6ea7c3757e22.png">

Perhaps we can put a close handler `onbeforeunload` that calls `URL.revokeObjectURL`. Although if you load that URL again, you'd expect it to still work.

**Comment by TimvdLippe** [comment]
@patrickhulce Your PR mentioned this issue and it has been merged. Does that mean this issue has been resolved and can be closed? Thanks for your work!

**Comment by ebidel** [comment]
This one is still open. That PR is for https://github.com/GoogleChrome/lighthouse/issues/1173

**Comment by Krinkle** [comment]
Still reproducible on Chrome 58.0.3016.0 canary with Lighthouse extension 1.5.2. Enabling it in Incognito performs the whole run and then opens a second tab with a blob url that leads to a 404 error.

**Comment by pavelloz** [comment]
Bug still present in Lighthouse 2.2.1 @ Chrome 59, OSX
