### ISSUE TITLE
PSI ignoring all objects using http/1.1 since Mar 3

### ISSUE THREAD

**Issue by tferik** [GoogleChrome/lighthouse#12222]
Since the Mar 3 Lighthouse update, we noticed the scores on some of our pages more than doubled. This is more than expected by just the change to support http/2. This particular site - (fishersci.com) is a mixture of http/1.1 and http/2 and it looks like Lighthouse isn't loading any of the resources hosted on the http/1.1 domain any more (beta-static.fishersci.com). So it's not loading any of the .css, .js, fonts and many images, giving a false score. We also noticed that some metrics can't be correct anymore, such as cumalitive layout shift went to 0 for all our pages.  I attached an image showing the drastic change in metrics on Mar 3rd for 4 different pages on www.fishersci.com:
https://www.fishersci.com/us/en/home.html
https://www.fishersci.com/us/en/contactus.html
https://www.fishersci.com/shop/products/pyrex-heavy-duty-griffin-beakers-7/0255525A#?keyword=beakers
https://www.fishersci.com/us/en/catalog/search/products?keyword=beakers

#### Provide the steps to reproduce
1. From a LH page, such as: https://developers.google.com/speed/pagespeed/insights/ run an analysis on https://www.fishersci.com/us/en/catalog/search/products?keyword=beakers
2. Notice in the screenshots of the page that none of the stylesheets are present.
  
#### What is the current behavior?
1. None of the resources hosted on beta-static.fishersci.com (http/1.1) are being loaded. Only the resources from www.fishersci.com (http/2) are loaded.
2. 
#### What is the expected behavior?
1. All the resources should be loaded. It should negotiate http/2 if possible, but revert to http/1.1 otherwise.

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: 7.1
* Chrome version: 88.0.4324.190 
* Node.js version:
* Operating System:
![FS_lighthouse_performance_anomaly](https://user-images.githubusercontent.com/80289038/110383820-b1c1ce80-8011-11eb-95db-454eca65c1d8.PNG)

**Comment by connorjclark** [comment]
Thanks for the report. We have similar reports already with the same root cause (#12219 #12216), but this issue seems the most useful filed so far so I'll dupe all the others into this.

We're investigating internally. Is there any detail you can share about how the beta-static.fishersci.com server is configured wrt http/1.1 / TLS?

**Comment by tferik** [comment]
This is the only info I got from our infrastructure engineer. Let me know if you need more details:
“I would say, nothing unusual with the server side setup around “beta-static.fishersci.com” and that it’s running on our legacy on-premise infrastructure that’s configured to support TLSv1.2 but without any forward secrecy/AEAD ciphers. “

**Comment by connorjclark** [comment]
Alright, we think we've identified the issue. A fix might be out within a couple of days.

**Comment by connorjclark** [comment]
Issue should be resolved as of ~2 hours ago. Can you confirm?

**Comment by privatenumber** [comment]
@connorjclark You closed https://github.com/GoogleChrome/lighthouse/issues/12210 as a duplicate, but the problem still persists for me. Will post details there.

**Comment by connorjclark** [comment]
@privatenumber I looked into the issue for this URL this morning, but didn't get anywhere useful because it seems the behavior is flaky. It was failing all morning, but more recently it always works. So perhaps it's been resolved somehow.

Some internal details lead me to believe that h2 specifically isn't the cause of this, so we'll close this issue (eventually, going to give some more time for others to comment); and if the issue on the URL you provided persists we'll re-open the other issue.

> FYI ...

This issue is tracking behavior in PSI, not Lighthouse CLI or DevTools.

**Comment by connorjclark** [comment]
We pushed a fix just now– @tferik, @privatenumber can you confirm?

**Comment by privatenumber** [comment]
Working consistently as of yesterday: https://github.com/GoogleChrome/lighthouse/issues/12210

Thank you @connorjclark !
