### ISSUE TITLE
 robots.txt is not valid- Lighthouse was unable to download a robots.txt file

### ISSUE THREAD

**Issue by owaishassan72** [GoogleChrome/lighthouse#12936]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

zomusk.com

### What happened?

I was running Lighthouse on my website and saw the error that "robots.txt in invalid" even though it is NOT.
I have tested my robots.txt file and it is fine and as per google's expectations.

### What did you expect?

I expected to not face this issue as there is no issue with my robots.txt file.
![image](https://user-images.githubusercontent.com/84473833/129964893-e64efb99-cd6c-45e4-b0af-70856b6f346c.png)
![image](https://user-images.githubusercontent.com/84473833/129964964-d1ae24b7-8699-42ee-bf84-26bf0d2bcde3.png)

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

 7.5.0

**Comment by asbhogal** [comment]
Hi @owaishassan72, I've just ran the Lighthouse PSI from my end using v8.0 and it confirms that your robots.txt is valid (please see screenshot.) From this, I assume that it may be an issue with the version of Lighthouse you're using. Maybe try updating to v8.0 and giving it a try and see if it recognises it on your end.

Hope this helps,
Aman
![Valid robots txt - Screenshot](https://user-images.githubusercontent.com/79533183/130048335-cb496c4f-092d-4f98-b39d-eedba1fff09c.png)

**Comment by AleksandrHovhannisyan** [comment]
I'm seeing this on web.dev/measure as well: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.aleksandrhovhannisyan.com%2F

![image](https://user-images.githubusercontent.com/19352442/131392984-db659f66-5dc4-41e5-8b22-f1d8a372d4ef.png)

**Comment by asbhogal** [comment]
Hi Aleksandr,

I've ran your site through the DevTools Lighthouse (7.5) and it detects your robots.txt fine:

![Lightouse - www aleksandrhovhannisyan com](https://user-images.githubusercontent.com/79533183/131533233-aa54a4eb-1387-492a-833f-dcae8835e3a8.png)

I've also ran it through the PSI and I'm getting the same message you are. For your case it seems the other way round - not sure why the PSI isn't detecting your robots.txt as the syntax looks correct to me, and I've checked it with Ryte's scanner and it crawls it fine . You can also check it with [Google's robots.txt scanner](https://support.google.com/webmasters/answer/6062598?hl=en) too. Hopefully Google can diagnose what the issue is @connorjclark

Hope this helps,
Aman

**Comment by brendankenny** [comment]
Yes, this looks like a new PSI issue. From https://github.com/HTTPArchive/httparchive.org/issues/422, https://httparchive.org/ is also failing. Confirmed with the direct API request to `'https://pagespeedonline.googleapis.com/pagespeedonline/v5/runPagespeed?url=https%3A%2F%2Fhttparchive.org%2F&category=SEO'`.

PSI updated to Chrome 92 yesterday, so this is hitting a new path (for PSI) in the `RobotsTxt ` gatherer:

https://github.com/GoogleChrome/lighthouse/blob/244364ce480da57bed7c105726804938cb5b86e0/lighthouse-core/gather/gatherers/seo/robots-txt.js#L41-L56

**Comment by mercadeowebcr** [comment]
Started seeing this error since yesterday. It now disappeared on one site https://geek.pontik.com but still appears in the sub domain https://radio.pontik.com and on the main site https://pontik.com. These are in separate servers.

**Comment by brendankenny** [comment]
This should be fixed for everyone now. Keeping open to track a permanent fix.

**Comment by nzsteve** [comment]
I am still seeing this as an issue with all WordPress Multisite installs even though there is a robots.txt file that can be viewed in the browser and no issues seen with Google robots testing tool.

Example content of robots.txt for https://bloxhams.co.nz/ and https://bloxhams.co.nz/robots.txt
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php

Screenshot from Chrome 95 Lighthouse 8.4
![lighthouse issue no robots](https://user-images.githubusercontent.com/65736385/139628768-2a941726-3bc8-45ca-93c5-1c9baa90658c.png)

**Comment by connorjclark** [comment]
I got the same using latest (master) LH, but only for the first attempt. Subsequent runs fetched the robots.txt successfully.

If you can consistently repro with the LH node CLI, please run with `-GA` and provide the value for `RobotsTxt` in `latest_run/artifacts.json`.

**Comment by beatquantum** [comment]
Please check your content-security-policy and add the following:

connect-src 'self';

It worked for me.
