### ISSUE TITLE
Lighthouse reports "NOT_HTML" when 103 Early Hints is used (Shopify urls)

### ISSUE THREAD

**Issue by MatinF** [GoogleChrome/lighthouse#13379]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.csselectronics.com/products/can-logger-sd-canedge1

### What happened?

I have previously been able to use [Google PageSpeed/Lighthouse](https://pagespeed.web.dev/) for analyzing various URLs on my website.

However, with the v9 update, I am now getting the below error in 80% of cases when I try using the tool on any URLs on my site:

```
Lighthouse returned an error: NOT_HTML. The specified page is not HTML (displayed as MIME type text / plain).
```

![image](https://user-images.githubusercontent.com/26184427/141977252-0e881000-1145-42e9-ab62-1429cf11f824.png)

Nothing has been changed on my site and everything was working fine before the v9 update. I was also not able to spot specific changes in the changelog that would explain this behavior. Any inputs would be highly appreciated

### What did you expect?

I would expect to be able to see the speed summary information for specific URLs on my website. 

### What have you tried?

I have tried this with various URLs on my website before/after the v9 update. I have never had a problem prior to the update, but after the update almost all my URLs fail 80%+ of the time.

In contrast, I seem to be able to use Lighthouse via the Chrome Development Tools when on a specific page on my site, though in that case I get an error about 20% of the time where Lighthouse states that it was not able to take any screenshots on the page, hence the Performance score is unavailable. 

### How were you running Lighthouse?

PageSpeed Insights

### Lighthouse Version

v9.0.0

### Chrome Version

Version 96.0.4664.45 (Official Build) (64-bit)

### OS

Windows

**Comment by DavidReider** [comment]
Hello! 

Just reporting that I am also experiencing this issue on a couple of websites since the update.

Two that were not working happened to be Shopify stores. 

One WordPress multisite was working. One WordPress single site was working.

**Comment by allthingscommerce** [comment]
+1

It looks like this can be replicated using any Shopify store URL.

**Comment by cramirez99** [comment]
+1
All Shopify URLs I'm tracking in Google sheets with the API responded with that error today.

**Comment by connorjclark** [comment]
103 Early Hint being new, our infra doesn't support it yet unfortunately. We're working on a fix.

**Comment by connorjclark** [comment]
internal: cl/181354429

**Comment by FrankTuit** [comment]
Having the same issue with the API and experiencing the same with a lot of Shopift URL's (90%)

@connorjclark Do you have any idea what time this might take to get solved?

**Comment by mikeantkowiakarcane** [comment]
Having the same issue on shopify urls.

**Comment by connorjclark** [comment]
No estimate as of now, but it is a priority. I'll update this thread when I have news.

**Comment by civilixed1996** [comment]
same issue on all shopify urls

**Comment by connorjclark** [comment]
We have prepared a fix and are validating it a bit more. This will likely be resolved in 1-2 weeks, if all goes well.

**Comment by connorjclark** [comment]
Looks like this is now fixed, as of today.

Provided URL no longer does 103 according to curl on my machine, but this does: https://ratiocoffee.com/

**Comment by daiky00** [comment]
For me is still not working here is the url.

https://pagespeed.web.dev/report?url=https%3A%2F%2Fomgkawaii.com%2F

the site is in Shopify

**Comment by rverelabs** [comment]
I'm still seeing the issue intermittently on Shopify stores, though it is rare. Shopify/Cloudflare may still be using 103 for a portion of requests.

**Comment by connorjclark** [comment]
Seems the fix has only partially gone out - atm ~90% of requests should work. Shouldn't be long before it's fully deployed.

**Comment by connorjclark** [comment]
Fix is out.

**Comment by ix-56h** [comment]
I'm still seeing this issue here : https://www.abeausejour.fr/ or here : https://www.abep94.fr/ but can't make any link between them.
