### ISSUE TITLE
Page Speed Insights "Unknown Error"

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14045]
https://fedyapparel.com/

### Discussed in https://github.com/GoogleChrome/lighthouse/discussions/14044

<div type='discussions-op-text'>

<sup>Originally posted by **zgonewild** May 22, 2022</sup>
Hi, new to github. Some searching led me here that I might be able to find the answer as to why page speed insights shows an "unknown error" when trying to to a site audit on my domain FedyApparel.com. Any help or tips in the right direction would be highly appreciated. Thanks!

![sc2](https://user-images.githubusercontent.com/106047115/169736098-9db7382e-9108-4577-aa2f-ec0cb0fafd22.png)
 </div>

**Comment by adamraine** [comment]
The page crashes when Lighthouse tries to load it. Looks like a Chrome bug of some sort but will need to get a min repro before filing a bug upstream.

**Comment by adamraine** [comment]
Crash seems to be happening after this CDP call:
https://github.com/GoogleChrome/lighthouse/blob/6e262f28a4e6a0d3d657a22a2e6f5191fc2d468f/lighthouse-core/gather/gatherers/css-usage.js#L84

Filed upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=1328304

**Comment by zgonewild** [comment]
Hey Adam, thanks for looking into this. Is this currently still where it stands "get a min repro before filing a bug upstream."

**Comment by adamraine** [comment]
I've already filed a bug upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1328304. You can follow along there for updates.

**Comment by zgonewild** [comment]
Appreciate it!

**Comment by adamraine** [comment]
This should be fixed in Chrome ToT. Expect the fix to reach stable in M105.

**Comment by zgonewild** [comment]
Hey adam, to my knowledge m105 should be out, although i still have the same error. Any suggestion on what I might do? thanks

**Comment by adamraine** [comment]
M105 is not even in beta right now. Current stable is M104.

https://chromiumdash.appspot.com/schedule

**Comment by zgonewild** [comment]
Appreciate the link, have a good weekend

**Comment by mj84** [comment]
Hello,
as M105 is available, is there also a schedule when this updated version will be used by PageSpeed Insights? Currently still receiving an "Unknown Error" at "Diagnose performance issues".

**Comment by ghalatransportationllc** [comment]
> https://fedyapparel.com/
> 
> ### Discussed in #14044
> Originally posted by **zgonewild** May 22, 2022 Hi, new to github. Some searching led me here that I might be able to find the answer as to why page speed insights shows an "unknown error" when trying to to a site audit on my domain FedyApparel.com. Any help or tips in the right direction would be highly appreciated. Thanks!
> 
> ![sc2](https://user-images.githubusercontent.com/106047115/169736098-9db7382e-9108-4577-aa2f-ec0cb0fafd22.png)

Hi guys I am facing same as your problem.... please anyone help me 
www.ghalagroup.online

 
![image](https://user-images.githubusercontent.com/122532325/212058793-2dc63f3a-0fb4-4cf4-afe1-4a8f09e0d124.png)
