### ISSUE TITLE
Lighthouse Accessibility Score not displaying on one page of the site

### ISSUE THREAD

**Issue by Beccal25** [GoogleChrome/lighthouse#15570]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://centennialsellcarforcash.com/MainBlog

### What happened?

All other pages on my site give a score for all metrics besides the blog page which is not showing a score for Accessibility.

![image](https://github.com/GoogleChrome/lighthouse/assets/149007290/1eec4096-c0f2-49d3-8b8e-ea16bf533cf0)

### What did you expect?

An accessibility score to be shown.

### What have you tried?

Changed font color and size on the site to comply with the contrast ratio, removed unnecessary code on the site and tried different layouts for the page.

### How were you running Lighthouse?

PageSpeed Insights, Chrome DevTools

### Lighthouse Version

11.0.0

### Chrome Version

118.0.5993.117

### OS

Windows

**Comment by adamraine** [comment]
This was fixed in Lighthouse v11.1 #15002

**Comment by trieu-hphuc96** [comment]
hi @adamraine, I'm still experiencing the same issue with Lighthouse v11.1
![image](https://github.com/GoogleChrome/lighthouse/assets/22952175/ba2d4908-5aef-4b3a-bd5d-07c4ac3c69e4)

![image](https://github.com/GoogleChrome/lighthouse/assets/22952175/20e12a8d-a3e8-4744-a59e-80af8e40ae99)

**Comment by adamraine** [comment]
@trieu-hphuc96 that appears to be this issue https://github.com/GoogleChrome/lighthouse/issues/15497

Accessibility score can be missing for a variety of reasons and I don't want this to be a catch all issue so I'm going to lock the thread. Please file a new bug report if you are experiencing something similar to this.
