### ISSUE TITLE
LCP is shown icorrectly in Lighthouse when document latency

### ISSUE THREAD

**Issue by vesan-83** [GoogleChrome/lighthouse#16732]
### FAQ

- [x] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [x] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [x] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://www.parfumerie.nl/clinique-take-the-day-off-lids-lashes-lips

### What happened?

When I use the Performance tab and record the page, I get stable results - faster server response leads to faster LCP, and vice versa. It looks correct.
But when I run Lighthouse, I often see different results, like the one I attached. - It doesn't look correct.

[895ms-77score.html](https://github.com/user-attachments/files/22742303/895ms-77score.html)
[150ms-72score.html](https://github.com/user-attachments/files/22742302/150ms-72score.html)

### What did you expect?

Improvements on document latency improves LCP like you see in Performance tab

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

12.8.1

### Relevant log output

```sh

```

**Comment by connorjclark** [comment]
There's a few things to keep in mind that can explain this:

* This page makes requests to 32 origins. The server response latency listed in the "Document latency" insight is just your main origin – but there's a lot more going on
* The LCP image is missing `fetchpriority=high` (see LCP request discovery insight), which means its unlikely it will be fetched before many other less important things. This seems like it'd be a large source of variance for LCP on this page
* For Lighthouse by default (and for these reports your shared), the default is to simulate a mobile device with Slow 4G network speeds. When latencies are exaggerated, so too is variance. This likely explains why you see difference behavior when running in the Performance panel, which by default has no network or CPU throttling.

**Comment by priscilamtzfraire** [comment]
I've also noticed similar inconsistencies. With the performance tab (with the 4x CPU slowdown and [the recommended network throttle](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md#the-mobile-network-throttling-preset)) I get 1.67 s on the LCP for [this page](https://www.parfumerie.nl/clinique-take-the-day-off-lids-lashes-lips).

[Trace-20251008T110836.json](https://github.com/user-attachments/files/22782734/Trace-20251008T110836.json)

With Lighthouse, under the same network conditions, I get 3.2 s.

[www.parfumerie.nl-20251008T111922.html](https://github.com/user-attachments/files/22782758/www.parfumerie.nl-20251008T111922.html)

**Comment by vesan-83** [comment]
@connorjclark , 

> This likely explains why you see difference behavior when running in the Performance panel, which by default has no network or CPU throttling.

I used network and CPU throttling:

<img width="222" height="70" alt="Image" src="https://github.com/user-attachments/assets/247bcc30-25fb-4b48-823e-dc00f40e71fb" />

**Comment by connorjclark** [comment]
Lighthouse's mobile CPU throttling is simulated (whereas the Performance panel is [throttled](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md)), and it 4x rather than 2.8x. Neither one is more correct.

I'm going to close this as I don't think there's a bug, just a mismatch of expectations. Different results are to be expected from different ways of throttling / simulating mobile performance. Some docs for further reading: https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md

**Comment by vesan-83** [comment]
@connorjclark, if you don't see the issue it doesn't means there is no issue. Why you closing the ticket wihtout even investigating or  proper explanation? All info is provided

There is some bug with calculation as it can be easily reproduced.

If Lighthouse results aren't explainable by Performance record - it's a bug

**Comment by benschwarz** [comment]
@vesan-83, you might have missed it, but @connorjclark pointed out:

> Lighthouse's mobile CPU throttling is simulated (whereas the Performance panel is [throttled](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md))

Lighthouse runs a trace, then applies simulated throttling, which means that the trace itself is going to be different from the result. Its a really common confusion in this error tracker, and something the team have responded to literally hundreds of times. 

tldr, do not expect that a regular performance panel trace will be the same as lighthouse. they're two different things!

**Comment by vesan-83** [comment]
@benschwarz, okay, I understand that Lighthouse uses simulation to make results closer to real-world conditions. However, does that actually explain the case I described?

I've done many measurements earlier - with and without various CPU/network throttling settings - and just ran another 25 tests to illustrate the issue.

For example, the attached result shows LCP = 0.7 s while the document latency is 830 ms. Lighthouse reports the same 0.7 s even when there's no document latency.

What's more interesting is: how can LCP be 0.7 s when the document isn't fully received until after 0.83 s and rendering hasn't even started yet?

[www.parfumerie.nl-20251011T173037.html](https://github.com/user-attachments/files/22864858/www.parfumerie.nl-20251011T173037.html)

**Comment by connorjclark** [comment]
There were some accuracy issues with the server response time in that audit that were resolved since 12.8.1. I'll double check during the work week that the latest version reports a server response time that aligns with LCP.

**Comment by vesan-83** [comment]
@connorjclark, I'm using 12.8.1 - is it fixed in this version, or only in a later one?

**Comment by vesan-83** [comment]
@connorjclark, @benschwarz,

The problem is still reproducible using version 12.8.2.

1) Latency 214ms, LCP 0.6s 

[www.parfumerie.nl-20251021T000942.html](https://github.com/user-attachments/files/23008821/www.parfumerie.nl-20251021T000942.html)

2) Latency 840ms, LCP 0.7s

[www.parfumerie.nl-20251021T000855.html](https://github.com/user-attachments/files/23008824/www.parfumerie.nl-20251021T000855.html)

LCP appears visibly slower (also confirmed by screenshots). The reported value of 0.7 s does not reflect the actual rendering speed.

**Comment by connorjclark** [comment]
> (me) There were some accuracy issues with the server response time in that audit that were resolved since 12.8.1. I'll double check during the work week that the latest version reports a server response time that aligns with LCP.

Don't see any issues in 13.0.

> The problem is still reproducible using version 12.8.2.

Please use 13.0 not 12. The issue of server response > LCP is either resolved in 13.0 or I cannot reproduce it.

> LCP appears visibly slower (also confirmed by screenshots). 

Those reports have simulated network throttling on. The reported LCP may be slower than what is observed.

**Comment by vesan-83** [comment]
@connorjclark 

>  The reported LCP may be slower than what is observed.

In my case, the reported LCP was lower

> Please use 13.0 not 12

I've upgraded Chrome today - it seems 12.8.2 is still the latest available for the .deb package.
