### ISSUE TITLE
Lighthouse treats "shrink-to-fit" property in meta-tag "viewport" as invalid

### ISSUE THREAD

**Issue by zhirzh** [GoogleChrome/lighthouse#2474]
In lighthouse audits,
this will pass:
`<meta name="viewport" content="width=device-width, initial-scale=1">`
this will fail:
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
with message `Invalid properties found: {"shrink-to-fit":"no"}.`

**Comment by patrickhulce** [comment]
Thanks for the report @zhaoz! Looks like our dependency for metaviewport parsing [hasn't been updated in quite some time](https://github.com/dontcallmedom/metaviewport-parser).

**Comment by zhirzh** [comment]
@patrickhulce that's not even my handle :joy:

**Comment by patrickhulce** [comment]
oops 😆  fixed! haha sorry for the same other similarly named LH-contributor :)

**Comment by ev1stensberg** [comment]
What should we do to chase this down?

**Comment by patrickhulce** [comment]
@ev1stensberg since that package doesn't seem very well maintained, we should probably add a temporary workaround to ignore `shrink-to-fit` in the audit for now

In the long term we'll need to decide if we want to...

* work with the owner to get a fix in place and published
* bring it into `third_party` and fix
* drop the package and parse the values ourselves

**Comment by ev1stensberg** [comment]
I can work on long term if you want to, better fix now than never :)

**Comment by hmelenok** [comment]
Guys please review it dontcallmedom/metaviewport-parser/pull/4

**Comment by hmelenok** [comment]
@patrickhulce i fix it for you

**Comment by hmelenok** [comment]
@patrickhulce GoogleChrome/lighthouse/pull/2863 with updated version

**Comment by paulirish** [comment]
fixed by #2863

**Comment by PatNeedham** [comment]
I'm still getting that same problem on the chrome extension @jamesvclements is referring to as well, ran on the default build of create-react-app.

**Comment by ev1stensberg** [comment]
Needs reinvestigation @patrickhulce

**Comment by brendankenny** [comment]
I think this is due to the release of the extension lagging behind (it's still on 2.3.0). We're hoping to do a release of 2.5.0 on all platforms early next week.

**Comment by Foorack** [comment]
Any update on this? I am still experiencing this in Chrome 62.

**Comment by patrickhulce** [comment]
@Foorack this was fixed on august 7, use Chrome Canary, the CLI, or the extension for latest LH version with the fix
