### ISSUE TITLE
Audit - aspect ratio is always throwing an error

### ISSUE THREAD

**Issue by jcdalton2201** [GoogleChrome/lighthouse#3551]
lighthouse 2.5.1 audit tests.

the Does not uses Images with appropriate aspect ratio is always failing. This test does not tell you which file is failing the test.  We then took all all of the images from the page and we still get this error.  We had to turn off our lighthouse test for the time because of this.  Here is an example page
https://jcdalton2201.github.io/progressive-app-test/ we have one img and its 80 X 80  the nat is 150 X 150.

**Comment by brendankenny** [comment]
Thanks for the report! That's definitely a bug...zero results is being turned into a 0 score, which is why it's failing but no image information is being displayed.

Sorry to have left you with such a head scratcher.

**Comment by brendankenny** [comment]
Fixed on master. We're planning on a release next week, so should be on npm then.

**Comment by matthiasg** [comment]
Sorry but the original issue report indicated two problems. That it triggered at all with two supposedly correct images and then still reporting with no images.

We get the same auditing error now too, but since the audit does not contain any info as to which image failed it is extremely hard to track down whether its a false positive. Which leaves us having to write a script to double check the site. 

Is the audit intended to contain an indicator as to where it failed anytime soon ?

**Comment by Hallya** [comment]
Hi ! 
Still getting this bug with 0 score on perceptual index speed but not img indicated.
