### ISSUE TITLE
running CLI gets cannot find module handlebars

### ISSUE THREAD

**Issue by jcdalton2201** [GoogleChrome/lighthouse#486]
When i run the cli i get the following error.
module.js:442
    throw err;
    ^

Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/report/report-generator.js:22:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by paullewis** [comment]
Is this off master?

**Comment by jcdalton2201** [comment]
the package.json has v1.0.2.
This was installed with npm install -g GoogleChrome/lighthouse
with npm version 3.9.5 node version 6.2.2
i then ran
```
npm explore -g lighthouse -- npm run chrome
```
then after chrome came up fine i ran
```
lighthouse https://smurfweather-jasontest0325381.rhcloud.com/
```
this is where i get the handlebars errors

**Comment by jcdalton2201** [comment]
oh and this is a very fresh install of node

**Comment by brendankenny** [comment]
Interesting. I'm running node v5.11.0 and running
```
npm install GoogleChrome/lighthouse
npm explore lighthouse -- npm run chrome
```
and then
```
./node_modules/.bin/lighthouse https://smurfweather-jasontest0325381.rhcloud.com/
```

I'm not seeing any issues; no runtime errors and the html report looks correct.

Maybe some interaction with node v6 or a change in npm? Travis is testing with the latest node and also not seeing a problem, but it installs via git.

**Comment by samccone** [comment]
This may be due to a bad publish if whoever published the latest version did it under 6
https://github.com/npm/npm/issues/5082

**Comment by paulirish** [comment]
btw @samccone this is installing from the repo, not using a published version.

----------------------------------------------

I can repro.

![image](https://cloud.githubusercontent.com/assets/39191/16467464/544f2d4e-3dfc-11e6-9289-b5ee78da613f.png)
![image](https://cloud.githubusercontent.com/assets/39191/16467474/5c237a66-3dfc-11e6-8d18-4ab7b63fc998.png)


Note the size of the installed deps. It's only the deps for the CLI that's in the root manifest. The `-core` manifest deps are not being installed.

**Comment by samccone** [comment]
w e i r d :bug:

**Comment by hsablonniere** [comment]
Has anyone found a way to fix it?

I'm having the same things as @paulirish screenshots with :

```
node v6.2.0
npm 3.8.9
```

**Comment by paulirish** [comment]
I have a workaround proposed in #500

**Comment by paulirish** [comment]
(The very manual workaround is to cd to your `node_modules/lighthouse` folder, cd into `lighthouse-core` and run npm install, then go into `lighthouse-extension` and npm install. )  But hopefully we can automate that with this fix.

**Comment by pierredewilde** [comment]
The manual workaround proposed by @paulirish solves dependencies issue but another error appears when running lighthouse CLI:

```
$ lighthouse https://ifixit-pwa.appspot.com/
Unable to connect to Chrome. Did you run ./scripts/launch-chrome.sh ?
```

**Comment by paulirish** [comment]
okay folks, the -g install should be fixed in master now. go ahead and try it.

@pierredewilde you'll want to do this instead: `npm explore -g lighthouse -- npm run chrome`  i'll update that error message.

**Comment by paulirish** [comment]
@pierredewilde fixed for ya 466beff

**Comment by pierredewilde** [comment]
Thanks for the more precise error message.

The -g install seems not yet fixed:

```
$ npm install -g lighthouse
...
/usr/local/lib
└── lighthouse@1.0.5
$ lighthouse --version
module.js:442
    throw err;
    ^

Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/report/report-generator.js:22:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
$ cd /usr/local/lib/node_modules/lighthouse/lighthouse-core
$ npm install
$ lighthouse --version
undefined
````

BTW `lighthouse --version` should return something like `1.0.5`.

**Comment by crhym3** [comment]
Same as @pierredewilde. Not fixed for me either (#503).

**Comment by crhym3** [comment]
Also, I don't see how https://github.com/GoogleChrome/lighthouse/commit/466beffc3499906feb195d707ed8991b1343e06f fixed this issue. This should be reopened.

**Comment by paullewis** [comment]
I'll take a look at this now, see if I can repro.

**Comment by crhym3** [comment]
Installing this locally from current master results in a slightly different error:

```
./node_modules/.bin/lighthouse --help
module.js:442
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/lighthouse/lighthouse-cli/index.js:21:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Installed with:

```
$ npm install googlechrome/lighthouse
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.0
...
npm info lifecycle lighthouse@1.0.5~postinstall: lighthouse@1.0.5

> lighthouse@1.0.5 postinstall /node_modules/lighthouse
> node _install_deps.js

npm --prefix /node_modules/lighthouse/lighthouse-core install /node_modules/lighthouse/lighthouse-core && npm --prefix /node_modules/lighthouse/lighthouse-extension install /node_modules/lighthouse/lighthouse-extension
...
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.0
...
/
`-- lighthouse@1.0.5  (git://github.com/googlechrome/lighthouse.git#f9bdc7f6958b0582b7ef490a44a5804fa650d493)
  +-- semver@5.2.0 
  `-- yargs@3.30.0 
    +-- camelcase@1.2.1 
    +-- cliui@3.2.0 
    | +-- string-width@1.0.1 
    | | +-- code-point-at@1.0.0 
    | | | `-- number-is-nan@1.0.0 
    | | `-- is-fullwidth-code-point@1.0.0 
    | +-- strip-ansi@3.0.1 
    | | `-- ansi-regex@2.0.0 
    | `-- wrap-ansi@2.0.0 
    +-- decamelize@1.2.0 
    +-- os-locale@1.4.0 
    | `-- lcid@1.0.0 
    |   `-- invert-kv@1.0.0 
    +-- window-size@0.1.4 
    `-- y18n@3.2.1 

npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm info ok
```

**Comment by paullewis** [comment]
@crhym3 Yours looks to be an issue based on the fact that deps might not be installed properly when npm installing non-globally. Going to close this again as #500 does solve it for global. We should deal with this in a separate issue.

**Comment by crhym3** [comment]
@paullewis it was a side not really. global install doesn't work for me either: #503.

**Comment by paullewis** [comment]
@crhym3 your install line was without the -g flag: `npm install googlechrome/lighthouse`, from what I can see.

**Comment by crhym3** [comment]
Hm.. do you not see the `-g` in #503?

**Comment by crhym3** [comment]
Sorry for the noise. This is indeed fixed in lighthouse. My local environment has npm scripts disabled, which is why it didn't install deps.

It's a shame though, that dependencies are installed using a script. I would suggest looking into solving it using the built-in deps management instead of using a post-install script. If at all possible.
