### ISSUE TITLE
"Site does not register a service worker." While it does

### ISSUE THREAD

**Issue by nicolas-t** [GoogleChrome/lighthouse#6342]
Edit: I've removed SW registration from the page https://bazaar.co/hello/  
So you on't be able to reproduce the bug anymore.
Other links are available further down in this thread.

#### Provide the steps to reproduce
1. Go to https://bazaar.co/hello/ with google chrome
2. Open **chrome dev tools** Audits tab, **make sure `Clear Storage` is checked**
3. Run an audit

#### What is the current behavior?
It says 
```
User will not be prompted to Install the Web App
Failures: Site does not register a service worker.
```
Meanwhile the `Applications` > `Service workers` tabs of the devtools says that my service worker is `activated and running`
I can also observe the cache effects of my service worker.

If you uncheck `Clear Storage` it seems to be working as expected.

#### What is the expected behavior?
The audit should not say `Failures: Site does not register a service worker.` 

#### Environment Information
- Chrome Version 69.0.3497.100 (64 bits)
- [vue-cli-pwa](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa)
- service worker loaded with https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-plugin-pwa/generator/template/src/registerServiceWorker.js

**Related issues**
https://github.com/GoogleChrome/lighthouse/issues/1815
https://github.com/GoogleChrome/lighthouse/issues/5527

(and thanks for you awesome work!)

**Comment by midzer** [comment]
Hi @nicolas-t 
While loading requested site, I've experienced service worker being installed while loading vast amounts of data. In my case it's been 22.8MB in 2minutes.
It is likely LH skips service worker detection after a certain amount of time, i.e. complete installing of service worker takes too long.

In general it's recommended to only include essential (small) resources into service worker, like .js, .css, .html files to make the app work at all. Seek for other caching opportunities for large media files like images or videos.

**Comment by nicolas-t** [comment]
Hello !

Thanks for taking a look, can you explain me where did you see the 22.8MB download ? 

Here I see around 2MB being downloaded: http://www.webpagetest.org/result/181024_X8_a38dbdaa3f958476f9dd6eed796f8f9e/

LH seems to agree : 
![image](https://user-images.githubusercontent.com/1765930/47452780-52a9e900-d7cb-11e8-865c-5ef79e58acfa.png)

---- 

More details about the page: 
It's doing a lot of "prefetch requests" for all the `js` and `css`.
The service worker (workbox) then preload those `js` and `css`.
images, videos and fonts are not preloaded by workbox.

Thanks

**Comment by midzer** [comment]
> Thanks for taking a look, can you explain me where did you see the 22.8MB download ?

Load your page with empty cache and open Dev Tools under Network Tab, you'll see data amount and time at the bottom of the table.

**Comment by exterkamp** [comment]
So I reran this in v4.0.0-beta and it registers a service worker and a full PWA badge, so I think this is fixed? Can you repro this still?

**Comment by nicolas-t** [comment]
It's not a problem anymore with chrome 71.0.3578.98.

**Comment by joshpoulain1** [comment]
> It's not a problem anymore with chrome 71.0.3578.98.

I'm still experiencing this. Service worker is registered and working great in Firefox. Chrome 72.0.3626.109 giving errors.

**Comment by nicolas-t** [comment]
You are right.
The bug reappeared for me too (72.0.3626.109)

Same steps to reproduce as detailed in [original post](https://github.com/GoogleChrome/lighthouse/issues/6342#issue-371681199).

**Comment by pimhooghiemstra** [comment]
Hello, I was experiencing this as well (chrome 72.0.3626.119) today. 

However, I was precaching quite large image files. Based on the comment of @midzer, I removed them (this is mere a test project) and gave it another try. The lighthouse scan passes and offers a score of 100 on PWA.

Note that I used Workbox from the CDN (https://storage.googleapis.com/workbox-cdn/releases/3.6.1/workbox-sw.js)

**Comment by tapankumar** [comment]
It is also not working for me.

i am on Version 72.0.3626.121 (Official Build) (64-bit)

Any suggestion?

**Comment by paulirish** [comment]
From #6935: another possible repro site: https://www.ackeller.ch/

**Comment by loicsalou** [comment]
same problem for me 
Version 77.0.3865.120 (Build officiel) (64 bits)

**Comment by mystic-cg** [comment]
I have the same problem.
Google Chrome: 78.0.3904.97 (Official Build) (64-bit) (cohort: Stable)

**Comment by kaito3desuyo** [comment]
I have a same issue.
Chrome 78.0.3904.108 Official Build 64bit

**Comment by h3d0** [comment]
Confirming the problem:
- Following the https://web.dev/add-manifest/
- Using https://manifest-good.glitch.me/ (which is supposed to demo WPA and Service Worker)
- Lighthouse **5.5.0**
- Google Chrome **79.0.3945.88 (Official Build) (64-bit)**

![image](https://user-images.githubusercontent.com/7346327/71321032-74c8f500-24bc-11ea-8ef8-203874833128.png)

The same output for any website one would try to test.

Confirmed on Google Chrome, Firefox and NPM Lighthouse.

Offtopic: taking into account Google's recent efforts to promote web-apps optimization for mobile devices, bugs like this create a serious obstacle to achieve those efforts. Fix it!

**Comment by patrickhulce** [comment]
I'm not able to reproduce any of the listed URLs. If you're experiencing this on your page, please file a new issue with repro steps and a URL.

> https://manifest-good.glitch.me/

Does not register a service worker, this page is an example of good *manifest* not a service worker. Lighthouse is correctly reporting here.

> https://www.ackeller.ch/

Fixed.

![image](https://user-images.githubusercontent.com/2301202/73308518-0fb49d80-41e6-11ea-84a6-3a6d55f77c2e.png)
