### ISSUE TITLE
Test My Site hung when testing CNN.com

### ISSUE THREAD

**Issue by safwans** [GoogleChrome/lighthouse#9040]
Here is a screenshot.
![Screen Shot 2019-05-13 at 10 46 45 AM](https://user-images.githubusercontent.com/16467231/57630901-77e62500-756c-11e9-8565-42a8c9c387a5.png)

https://screenshot.googleplex.com/DRNCFZEOQFx

**Comment by exterkamp** [comment]
This is a known issue, has been fixed in Chromium waiting on a PSI update.
#8113 
https://bugs.chromium.org/p/v8/issues/detail?id=9105

**Comment by safwans** [comment]
Quick follow up. Web.dev still fails when testing cnn.com. Do you know when PSI is going to use updated Chromium?

**Comment by connorjclark** [comment]
@safwans we don't have a plan for the next update as of now. If you follow [PSI group](https://groups.google.com/forum/#!forum/pagespeed-insights-discuss) you'll be alerted of the fix when it happens.
