### ISSUE TITLE
No Lighthouse Performance Score

### ISSUE THREAD

**Issue by KathleenA** [GoogleChrome/lighthouse#9848]
#### Provide the steps to reproduce
1. Go to https://www.giga.de/unternehmen/huawei/news/beeindruckende-zahl-beweist-deshalb-muss-sich-apple-vor-huawei-fuerchten/ 
2. Open DevTools and run Lighthouse Audit with setting: Mobile, Performance, Simulated Slow 4G

#### What is the current behavior?
The audit doesn't end and no score is calculated. 

#### What is the expected behavior?
The audit ends and shows a score.

#### Environment Information
Google Chrome Version 77.0.3865.90

#### Additional Information
We use Speedcurve for our Performance tests. Since 14 August we've got no Lighthouse Performance Score. On 3 October it worked for one day (see image). 
<img width="1099" alt="Bildschirmfoto 2019-10-16 um 10 33 53" src="https://user-images.githubusercontent.com/35454141/66903138-34ec1a00-f002-11e9-8f9c-a55d26e731ea.png">

Lighthouse Test Log from WebPageTest, 16. October, 9am CEST: 
[Lighthouse_test_log_16_october_9am_CEST.txt](https://github.com/GoogleChrome/lighthouse/files/3733361/Lighthouse_test_log_16_october_9am_CEST.txt)

**Comment by patrickhulce** [comment]
The log says the Lighthouse process was killed. You'll need to ask Speedcurve why they prematurely kill Lighthouse processes.

**Comment by patrickhulce** [comment]
Thanks for filing @KathleenA! This page has massive data URLs that take a long time to parse and the Lighthouse run is killed prematurely (but does eventually finish).

We'll improve the speed on our side which should fix this issue.

**Comment by patrickhulce** [comment]
Fix up at #9849

**Comment by KathleenA** [comment]
Hi @patrickhulce,
just to inform you: issue is not solved. It's not possible to get a LPS in DevTools. The behavior is the same as described above.

**Comment by patrickhulce** [comment]
DevTools runs ~6-12 weeks behind master here, so you won't see the fix in stable Chrome until mid-December.

**Comment by KathleenA** [comment]
Ah ok, thanks for the info :)
